language: python
matrix:
    include:
        - python: 3.8
          dist: xenial
          sudo: true
services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py && flake8"
